### ISSUE TITLE
调用dubbo接口一直报错

### ISSUE THREAD

**Issue by ninpu** [dubbo/dubbo2.js#14]
hi
我在egg新开工程，尝试调用线上已存在的dubbo服务。一直报错，不知道是什么原因。

`Fail to decode request due to: RpcInvocation [methodName=xxx, parameterTypes=null, arguments=null, attachments={path=yyy, input=199, dubbo=2.8.4, version=}]`

dubboVersion: 2.8.4

**Comment by hufeng** [comment]
hi @ninpu 看错误信息应该是参数序列化的时候失败了。 方便贴一个代码片段吗？
我们需要所有的参数都是js-to-java进行转化过后的。

**Comment by hufeng** [comment]
可以通过debug=dubbo* npm run dev 看到更详尽的错误信息

**Comment by ninpu** [comment]
非常感谢解答，我隐去一些关键信息

首先是eggjs中的Dubbo.ts
```
const dubbo = Dubbo.from({
    application: { name: 'app-name' },
    register: 'xxx.xxx.xxx.xxx:xxxx',
    dubboVersion: '2.8.4',
    interfaces: ['com.xxx.xxx.api.XXApi']
});

const spApiService = dubbo.proxyService<IDemoService>({
    dubboInterface:'com.xxx.xxx.api.XXApi',
    version: '',
    timeout: 5000,
    group: '',
    methods: {
        getPcPageByUrlKey(urlKey: string) {
              return [java.String(urlKey)]
        },
    }
});
```

对应的java interface代码如下
```
public interface XXApi {

    /**
     * 根据urlKey 获取信息
     *
     * @param urlKey
     * @return
     */
    ResultData<SPPageTO> getPcPageByUrlKey(String urlKey);

}
```

**Comment by hufeng** [comment]
@ninpu 奇怪 😆 就一个参数没有什么特别 怎么就序列化失败了呢， 可以看看debug=dubbo* npm run dev 更详尽的信息吗 我们也是用的egg。

**Comment by ninpu** [comment]
```
{ res: null,
  err: Error: invoke com.ope.sp.api.XXApi#getPcPageByUrlKey was error, 0�Fail to decode request due to: RpcInvocation [methodName=getPcPageByUrlKey, parameterTypes=null, arguments=null, attachments={path=com.ope.sp.api.XXApi, input=160, dubbo=2.8.4, version=}]
    at Object.decode (/User/ninpu/egg-dubbo-test/node_modules/dubbo2.js/es7/decode.js:71:18)
    at DecodeBuffer.SocketWorker._onSubscribeDecodeBuff [as _subscriber] (/User/ninpu/egg-dubbo-test/node_modules/dubbo2.js/es7/socket-worker.js:43:35)
    at DecodeBuffer.receive (/User/ninpu/egg-dubbo-test/node_modules/dubbo2.js/es7/decode-buffer.js:111:22)
    at SocketWorker._onData.data (/User/ninpu/egg-dubbo-test/node_modules/dubbo2.js/es7/socket-worker.js:67:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20) 
}
```
我这边vscode里执行`debug=dubbo* npm run dev`没有更多的信息，这是我打印出来的报错。
另外我做了个尝试，把methodName改成一个Java里不存在的名字，不放入参，执行后也是这样的报错。

**Comment by ninpu** [comment]
刚向开发同学了解了下 我们是用的是dubbox 不知道这个是不是有影响

**Comment by hufeng** [comment]
@ninpu 目前我们实现的是dubbo + hessian 2, 估计dubbox的底层的二进制的协议有变化 我来看下

**Comment by hufeng** [comment]
@ninpu 有问题不怕 我和同学们全力支持 我们还写了自动把java转化为ts的工具

**Comment by ninpu** [comment]
@hufeng 支持👍

**Comment by ninpu** [comment]
@hufeng 我根据https://blog.csdn.net/warrah/article/details/54317227的方案，进行了修改，可以正常获取了。

**Comment by hufeng** [comment]
@ninpu 我对比了下源码，
dubbox 和 dubbo 在encodeRequestData的时候有一些不同，
dubbo,
![image](https://user-images.githubusercontent.com/533008/39858366-ea8b8c42-5468-11e8-9eab-83ee13594e6a.png)

dubbox
![image](https://user-images.githubusercontent.com/533008/39858380-f3050024-5468-11e8-9b97-8d8f71e12815.png)

我在encode的时候根据是不是dubbox，多写一个-1就可以了 估计

**Comment by ninpu** [comment]
非常感谢😂 前端不是很了解dubbo 折腾了一天学了好多东西

**Comment by hufeng** [comment]
@ninpu 我和你也一样，也是一个前端， 喜欢node 喜欢折腾。回头把我折腾的这个过程分享给你。

**Comment by ninpu** [comment]
👍👍👍

**Comment by hufeng** [comment]
@ninpu dubbo2.js@1.0.2 supported dubbox
