### ISSUE TITLE
现在能够通过 node 在 Dubbo 上注册服务吗？

### ISSUE THREAD

**Issue by gaochengyidlmu** [dubbo/dubbo2.js#16]
第一次使用 Dubbo，以下是我对本项目的理解，如有错误，望不吝赐教。

1. 本项目是一个通过 node 实现的 Dubbo 客户端
2. 本客户端的作用是订阅服务，不能发布服务
3. 使用时，需要编写（或 Java 生成）对应的代理服务文件
4. 代理服务的作用：业务代码调用时，由代理服务组装数据后，执行转发

其中关于第二点是我最困惑的，是我没找到 Node 发布服务的方式，还是 Dubbo 只能通过 JAVA 进行服务发布。

**Comment by hufeng** [comment]
hi @gaochengyidlmu 你的理解是对的，目前我们提供是node和dubbo调用的consumer的客户端，么有想过用node去替代java的去暴露dubbo的服务出来，尽管可以做，我们内部也有小伙伴在讨论是不是可以加上这样的能力，我还在思考有没有必要。

**Comment by hufeng** [comment]
3. 使用的时候，本质上确实需要我们编写java的代理服务文件，所以我们写了一个翻译器的小工具可以把java的代码自动转成typescript(如果不用typescript，可以用typescript再生成javascript文件)方便小伙伴调用，希望可以做到无缝的开发体验。我们内部的实践就是这样。

**Comment by hufeng** [comment]
代码的ppt目录有我们内部的分享

**Comment by gaochengyidlmu** [comment]
@hufeng 感谢答疑~
我现在能找到的 Dubbo 的 Node 模块，似乎都是 Consumer Client，没有 Provider Client 。

**Comment by gaochengyidlmu** [comment]
@hufeng 感谢答疑~
本来我还有些纳闷，为啥你们只做了 Consumer Client，没做 Provider Client，直到看了你们的 PPT。
说实话，看完你们的 PPT，我已经开始脑补前后端大作战了~😆
（一群对后端欲求不满的前端，开始自己动手、丰衣足食了，佩服佩服）

/***************** 割 ****************/
如果你们是想通过 node 中间件，来达到大前端的目的，那我觉得现在就已经够用了。

不过我还是描述下我现在遇到的问题：
1. 公司技术栈全 Node
2. 新产品需要上微服务
3. RPC 框架选型困难，gRPC 配套不全，文档稀少；Dubbo 功能齐全，但不支持 Node；zeroRPC、dnode 已经许久没有维护了

不知道对于我这样的情况，有没有什么建议。
再次感谢

**Comment by hufeng** [comment]
建议后端服务还是java比较好一点，生态成熟稳定，dubbo也比较好用。我们也是这样的，后端的中台服务全是java的。

**Comment by hufeng** [comment]
这样1 + 1 > 2的效果，中台稳定高效， BFF+前端快速迭代 😆双赢。

**Comment by gaochengyidlmu** [comment]
唔，那再想想吧~

**Comment by brucecodezone** [comment]
@gaochengyidlmu 试试http://hprose.com/，我这个业务线也是全部nodejs,用起来感觉挺好的
