### ISSUE TITLE
add invoke type json-rpc?

### ISSUE THREAD

**Issue by ImHype** [dubbo/dubbo2.js#20]
不知有没有实践过 `json-rpc` 的调用方式，关于 rt 以及并发上，能否接受，个人觉得 json-rpc 更适合跨语言调用

**Comment by hufeng** [comment]
O(∩_∩)O~~ 这个我们还真可以好好的讨论下

**Comment by hufeng** [comment]
https://github.com/QianmiOpen/dubbo-node-client 这个是我们现在的一个实现版本

**Comment by hufeng** [comment]
无缝开发体验，翻译师要直接从java直接转ts的对象的json格式的类型定义

**Comment by ImHype** [comment]
是否在 dubbo2.js 中集成比较好，支持 invoke type 选择

**Comment by hufeng** [comment]
可以，想法和你一致，支持协议切换

**Comment by ImHype** [comment]
嘻嘻 那这块我来整把

**Comment by hufeng** [comment]
hi @ImHype 进展如何，需要帮助吗？

**Comment by sunchuanleihit** [comment]
这个事情现在有进展吗

**Comment by hufeng** [comment]
暂时没有，虽然json-rpc也是我厂出品

这个需要和我们的翻译器一起完成 才能更好的解决开发体验的问题

目前使用原生的协议在内部开发体验已经不错

抽时间我和翻译器晓东同学讨论下

孙传磊 <notifications@github.com> 于2019年4月30日周二 下午3:25写道：
