### ISSUE TITLE
接口方法参数List<User>，调用后，后端变成了List<hashMap>了，导致类型不对报错，不知道什么原因？

### ISSUE THREAD

**Issue by 15168326318** [dubbo/dubbo2.js#25]
1.后端方法
   
![qqqqqqqq](https://user-images.githubusercontent.com/38483933/41343097-4a8836c2-6f30-11e8-9f45-33a55d186766.png)

2.ts文件如下：
![ts](https://user-images.githubusercontent.com/38483933/41343112-54ffc052-6f30-11e8-9656-48a392ef8806.png)

3.前端调用：
![qq 20180613172904](https://user-images.githubusercontent.com/38483933/41342725-88db2b92-6f2f-11e8-95c4-42fde2ab1128.png)

4.结果是List<HashMap>,而不是参数类型List<User>.所以导致类型转换报错。而且bigDecimal值也不对：100.06变成1了

![aaaaa](https://user-images.githubusercontent.com/38483933/41342837-c3d19308-6f2f-11e8-9179-c7e18cf538a8.png)

**Comment by creasy2010** [comment]
@15168326318 
试下这种方式呢.  
java('java.util.List',[
      java('com.xxxx.User', {
            name: 'bar' ,
            id:33
            .....
});
])

转换时 , 如果不是翻译师生成的对象(如:list ,) 会直接把参数返回.  所以new user 会处理错误..

**Comment by hufeng** [comment]
@15168326318 我来定位下。

**Comment by creasy2010** [comment]
或者这种方式 
java('java.util.List',[
       new User(...).__fields2java()
])

我们提倡的最佳实践是单参数. 这样能避免很多问题..

**Comment by 15168326318** [comment]
@creasy2010   你们应该按alibaba的dubbo支持的参数来实现，他们是没限制的。 微服务dubbo不太可能按你们的限制来做的，对吧。

**Comment by creasy2010** [comment]
@15168326318 是的，只是建议；
　传任意参数都是可以调通的，但 **开发体验**却没那么好，就像你这个例子，我们在开发过程中**需要**关注hessian.js能识别的对象结构　而不是本能的写一个javascript的对象；
目前我们还没想到好的方案打通这一点？

**Comment by lileilei** [comment]
@creasy2010 
```
var combineArray = function (type, value) {
  var values = null;
  if (value) {
    values = [];
    for (var i = 0, len = value.length; i < len; i++) {
      values.push(combine(type, value[i]));
    }
  }
  return {
    $class: '[' + (type.name || type),
    $: values
  };
};
`
```
`values.push(combine(type, value[i]));`的时候判断一下是否有__fields2java方法有则调用不知道能否解决这个问题？

**Comment by creasy2010** [comment]
这是那块的逻辑？？

**Comment by lileilei** [comment]
@creasy2010  是的。应该阔以哦

**Comment by creasy2010** [comment]
你看的真仔细,, 哈哈, 
确实是可以的, 而且有一个更好的位置 .放这段逻辑 .. 下面会详细说明

上次跟[胡峰](https://github.com/hufeng)讨论过这件事, 我把讨论的内容和例子在这里阐明下...  

## 转换基本类型数据示例 
翻译师其实做了两件事, 
1. 编译时, 把java接口代码转换为typescript文件;
2. 运行时, 把js对象转换为hession.js协议能识别的对象;  

而此issue中一直就是围绕2讨论, 因为针对java的基本类型, 我们并没有生成转换代码,需要手工去写hession.js识别的结构;

我们可以在argumentMap 方法中写转换的逻辑 . 

[示例代码](https://github.com/dubbo/dubbo2.js/blob/master/examples/hello-egg/app/dubbo/providers/com/alibaba/dubbo/demo/DemoProvider.ts)


```typescript 
 
export const DemoProviderWrapper = {
  sayHello: argumentMap,
  test: argumentMap,
  echo: argumentMap,
  getUserInfo: argumentMap,
};

```


你上面的例子伪代码如下:  
```typescript

export const DemoProviderWrapper = {
  getUserList:(userList:Array<User>)=>{
      // 注: 转换的逻辑是自动生成的 
      // TODO null undefinded的情况还要排除
      return java('java.util.List',userList.map(user=>user.__fields2java()));
   },
};
```

但是 遇到java多态 就变得麻烦了...  这也这是为什么现在没有做这一块...  

## 为什么没有做
估算下.  上面的解决方案能解决97%的场景, 但碰到java多态就会被"破功"了.. 尤其是参数类型不能通过次序+类型来判断的情况 ,
@lileilei

**Comment by CodeLittlePrince** [comment]
建议把这个场景放在demo里，一个上午老泪纵横 T T
