### ISSUE TITLE
Java类转为node后子类丢失问题

### ISSUE THREAD

**Issue by dongzhangli** [dubbo/dubbo2.js#29]
provider
``` java
public interface PaymentProvider{
PayResultBO guaranteePayment(PaymentBO paymentBO, PaymentMethod paymentMethod, String realPayeeUserId, EnumTradeChannel enumTradeChannel)
            throws BaseException;
}
```
父类
``` java
public abstract class PaymentMethod extends BaseBean implements Cloneable {
}
```

子类
``` java
public class PaymentMethodOLP extends PaymentMethod {
}
```
以上代码，
期望的是Java类转换成node后，依赖包中包含PaymentProvider、PaymentMethod、PaymentMethodOLP等文件。
结果转换成node后只包含了PaymentProvider和PaymentMethod。
PaymentMethodOLP文件丢失了

**Comment by hsiaosiyuan0** [comment]
@dongzhangli 并不会全量的将所有的 Java 文件转换成等价的 TS 文件，而是由 `Provider` 为入口点，收集并转换它所依赖的定义。从你提供的代码来看，`PaymentProvider` 只依赖了 `PaymentMethod` 并不依赖 `PaymentMethodOLP`。

**Comment by dongzhangli** [comment]
实际在消费方是new PaymentMethodOLP，而不是PaymentMethod，在消费方找不到PaymentMethodOLP类。
这可能是接口设计的问题...
``` java
PaymentMethod  paymentMethod = new PaymentMethodOLP();
paymentProvider. guaranteePayment(paymentMethod)
```

**Comment by creasy2010** [comment]
+1 
如果这方面有强烈需求 , 可以搞个pr , 处理如下:
判断如果参数为abstract 或 interface 扫包下实现的类进行单独翻译,而方法的参数类型声明为  ? extend xx

这个issue先关闭了.
