### ISSUE TITLE
从java的jar包translator错误

### ISSUE THREAD

**Issue by Blackgan3** [dubbo/dubbo2.js#30]
我的dubbo.json配置文件为：
```js
{
  "output": "./src",
  "entryJarPath": "./java/dubbo-demo/qifutong-api/target/qifu-labourer-client-1.1.6-SNAPSHOT.jar",
  "libDirPath": "./java/dubbo-demo/qifutong-api/target/lib/"
}
```
其中的jar包和依赖包都是有的。
然后npm install interpret-dubbo2js
运行interpret -c dubbo.json
运行结果为：
```js
Output at: C:\Users\ADMINI~1\AppData\Local\Temp\jexpose2045571442071863293

elapsed: 81.317s

read jar ast file C:\Users\ADMINI~1\AppData\Local\Temp\jexpose2045571442071863293\output\deflated.json
Translation completed

```
第一个是包没有输出到我指定的路径，其二是输出的文件中output文件夹下只有一个deflated文件，里边内容为：
```js
{
  "classes":{},
  "providers":[]
}
```
请问下这是什么原因呢？

**Comment by hsiaosiyuan0** [comment]
应该是 service name 没有以 `Provider` 结尾，参考 https://github.com/dubbo/dubbo2.js/issues/23，后续会增加这方面的支持

**Comment by Blackgan3** [comment]
还确实是这样的，
```js
package com.service;
import com.dto.AppUserDto;

public interface AppUserService {
    String getTokenById(String var1);
    OperationResult saveAppUser(AppUserDto var1);
}
```

service后边没有provider,所以现在这个功能我还是用不了的对吧？

**Comment by hsiaosiyuan0** [comment]
@Blackgan3 是的，目前的话只有使用既定的命名规范，即以 `Provider` 结尾

**Comment by Blackgan3** [comment]
@hsiaosiyuan0  https://github.com/hsiaosiyuan0/jexpose/pull/7

**Comment by 15168326318** [comment]
改成以Service结尾的基本就行了

**Comment by 15168326318** [comment]
接口都是这样命名的，规范啊

**Comment by creasy2010** [comment]
点赞,...  我来合下.

**Comment by Blackgan3** [comment]
@creasy2010 使用正则是要支持多个不同的后缀名？那就需要改下endsWith那个判断了，不过大部分的java代码里，Service name的后缀名都是统一的吧。

**Comment by creasy2010** [comment]
只是后缀名判断的问题在于会误判.
我们以provider结尾 之前就遇到过. 非dubbo接口文件也是以provider结尾; 
以service结尾可能有更多误判的情况 ..  因为这个更通用 , 哈哈..  

用正则来表达这个判断 , 我们可以添加更灵活的判断,排除误判... 

@Blackgan3

**Comment by 15168326318** [comment]
加了后缀名运行报错啊。
![aaaaaaa](https://user-images.githubusercontent.com/38483933/42070270-35119d42-7b88-11e8-8d40-92b417ecf635.png)

**Comment by creasy2010** [comment]
看报错, 是json定义格式不正确 ..  
刚的pr我正在测试,还没发上去 .
带其他几个改进一并发包

**Comment by creasy2010** [comment]
已经发过了.

**Comment by Blackgan3** [comment]
点赞
@creasy2010
