### ISSUE TITLE
如何设置上下文变量？

### ISSUE THREAD

**Issue by ninpu** [dubbo/dubbo2.js#36]
HI，我想在dubbo调用时传递userid等值，但不想在每个接口都设个变量。请问能否通过上下文的方式传递值？谢谢~

**Comment by hufeng** [comment]
可以的，你的场景是不是要将userid放入dubbo的attachment字段，然后传递给dubbo的服务方？

**Comment by ninpu** [comment]
@hufeng 没错，这个有example吗？

**Comment by hufeng** [comment]
@ninpu  我来把这个扩展的更灵活一点，我们内部的log全链路跟踪和你的场景是一样的 比如需要把一个请求的uuid带着，我来把attachment在context中扩展出来 方便你很简单的完成这个需求

**Comment by hufeng** [comment]
@ninpu 

use dubbo2.js@2.1.8

```typescript

dubbo.use(async function traceUserId (ctx: Context, next) {
  ctx.attachments = {
   userId: 'xxx'
 }
 await next();
});

```

**Comment by ninpu** [comment]
@hufeng 非常感谢 我用这个试试 👍👍👍
