### ISSUE TITLE
接口超时的疑问

### ISSUE THREAD

**Issue by ninpu** [dubbo/dubbo2.js#37]
hi
我现在egg工程中，service内new Dubbo，用proxyService注册方法，然后调用。
第一次能成功，同一个接口调用第二次就会超时。
如果重启工程又能进行一次调用，第二次超时。有碰到过这种情况的吗？

代码大致如下：
`

import { Context, Service } from 'egg';
import { Dubbo, java, TDubboCallResult, Context as DubboContext } from 'dubbo2.js';

export default class MyService extends Service {

    constructor(ctx: Context) {
        super(ctx);
    }

    /**
     * 新建模板活动
     */
    public async createActivity(arg1, arg2) {
        const { ctx } = this;
        const { dubboGroup, dubboBase } = ctx.app.config;

         // 创建dubbo实例
        const dubbo = new Dubbo({
            ...dubboBase.myConfig,
            dubboInvokeTimeout: 30,
            service: { myApiService: this.myApiService },
        });

        dubbo.subscribe({
            onTrace: (msg) => {
                this.logger.info(msg);
            },
        });

        const doSometing = dubbo.service['myApiService'].doSometing;
        const result = await doSometing(arg1, arg2);
        
        if (result.err) {
            this.logger.error(result.err);
            this.ctx.throw('dubbo服务出错，请联系管理员');
        }

        return result.res;
    }

    private myApiService = (dubbo) => {
        const { ctx } = this;
        const { dubboGroup, dubboBase } = ctx.app.config;
        return dubbo.proxyService({
            dubboInterface: 'my.dubbo.interface',
            version: '0.0.0',
            group: dubboGroup.myConfig,
            methods: {
                doSometing(arg1, arg2) {
                    return [
                        java.String(arg1),
                        java.String(arg2)
                    ];
                },
            },
        });
    }

}

`

**Comment by ninpu** [comment]
感觉有点类似于连接未释放

**Comment by hufeng** [comment]
我来写个单元测试测试下，dubbo对象应该是单例 这样写太费了 每次调用都要创建一个dubbo对象 另外你的代码补齐不生效了const doSometing = dubbo.service['myApiService'].doSometing; 不需要这样写的

可以参见example/hello-egg的整合方式

**Comment by ninpu** [comment]
@hufeng 👍根据example的方式搞定了

**Comment by hufeng** [comment]
dubbo这个对象应该是单例 他里面做了很多事情，建立队列，连接zk，创建socket池，调度等 比较重

**Comment by hufeng** [comment]
另外像example你会获得更好的代码提示
