### ISSUE TITLE
如何支持多application

### ISSUE THREAD

**Issue by ninpu** [dubbo/dubbo2.js#38]
HI，
现在遇到一个情况，我需要连接2个application。如果我对每个application new Dubbo的话，就破坏了单例模式，导致超时。
请问现在是否支持连接同一register上的不同application？

**Comment by hufeng** [comment]
是支持的啊，只要dubbo的service对象包含了你要访问的服务就可以了啊。不需要每次new dubbo，dubbo对象是一个容器，他对整个zookeeper注册中心的服务做代理。

**Comment by ninpu** [comment]
@hufeng 感谢 
我仔细看了下文档，发现可以用 application: { name: ['appA', 'appB']},
只要在同一个zk集群就行

**Comment by hufeng** [comment]
//封装service - 手写，或者通过interpret代码自动生成
![image](https://user-images.githubusercontent.com/533008/42442724-0bd8d274-839e-11e8-9756-1738182f87f4.png)

//创建dubbo单例对象，将要代理的service传入
![image](https://user-images.githubusercontent.com/533008/42442736-146cd426-839e-11e8-9717-b80cbdaa5507.png)

//动态设置调用dubbo的group,version等信息
![image](https://user-images.githubusercontent.com/533008/42442752-1b8b04a8-839e-11e8-9a92-7b4a00e2e6ab.png)

//controller或者其他地方就可以很方便调用
![image](https://user-images.githubusercontent.com/533008/42442890-7ee187ac-839e-11e8-82cb-f915455abcb5.png)

//调用时有非常爽的代码提示 服务级别
![image](https://user-images.githubusercontent.com/533008/42442915-945ef0a6-839e-11e8-8479-fa1447c7eca6.png)

//方法级别
![image](https://user-images.githubusercontent.com/533008/42442934-a22cd36a-839e-11e8-98b8-0ec006bc6e93.png)

**Comment by hufeng** [comment]
@ninpu 是的 亲 😆

**Comment by hufeng** [comment]
{application:{name: ‘一个字符串就好’}}

**Comment by ninpu** [comment]
👍昨天根据这个demo已经完成单例模式了。只是今天发现要调同一个集群的不同的application。
不过我发现application name并不影响dubbo调用api。

**Comment by hufeng** [comment]
@ninpu 是的 application: {name} 是告诉dubbo-admin那边 我们在消费 😆
