### ISSUE TITLE
could not find any agent worker with com.xxx.xxx

### ISSUE THREAD

**Issue by creasy2010** [dubbo/dubbo2.js#39]
在开发过程中 调用 com.qianmi.mc.api.buyer.BuyerActivityQueryProvider 出现异常.跟踪如下:  

![image](https://user-images.githubusercontent.com/1592277/42721632-9119ccce-8770-11e8-941b-01580a31ef6a.png)

dubbo 启动时,providerurl信息,可以看出BuyerActivityQueryProvider 并没有相应的provider
![image](https://user-images.githubusercontent.com/1592277/42721626-719459c8-8770-11e8-964f-7701e10f0feb.png)
登陆 zookeeper 查看 ,确实没有
![image](https://user-images.githubusercontent.com/1592277/42721645-bb38f8fe-8770-11e8-935b-ee1be182ce8c.png)

查看 dubbo源代码 . 在调用接口,如果没找到相应的SocketWorker,则会报:Could not find any agent worker 
```typescript

  private _handleDubboInvoke(requestId: number) {
    //get request context
    const ctx = queue.requestQueue.get(requestId);
    //get socket agent list
    const agentAddrList = this._zkClient.getAgentAddrList(ctx);
    log('agentAddrSet-> %O', agentAddrList);
    const worker = this._serverAgent.getAvailableSocketWorker(agentAddrList);

    //if could not find any available socket agent worker
    if (!worker) {
      const {requestId, dubboInterface, version, group} = ctx;
      const msg = `requestId#${requestId}:Could not find any agent worker with ${dubboInterface}#${version}#${group} agentList: ${agentAddrList.join(
        ',',
      )}`;
      const err = new ScheduleError(msg);
      this._handleFailed(requestId, err);
      log(err);
      traceErr(err);
      return;
    }

    ctx.invokeHost = worker.host;
    ctx.invokePort = worker.port;

    const providerProps = this._zkClient.getDubboServiceProp(ctx);
    queue.consume(ctx.requestId, worker, providerProps);
  }
```

**Comment by hufeng** [comment]
1. 可能真的是zk中就没有这个注册的dubbo service url
2. 可能是zk发生了disconnected, 导致负载重启之后，不会再连上，因为zk不会watch没有反应能力了

**Comment by shige8023** [comment]
怎么解决的

**Comment by shige8023** [comment]
@creasy2010
