### ISSUE TITLE
 err: Error: uuid:  invoke com.sitech.hsf.Interface.ServerA#sayHello was error,

### ISSUE THREAD

**Issue by SmartKarven** [dubbo/dubbo2.js#44]
你好： 
err: Error: uuid:  invoke com.sitech.hsf.Interface.ServerA#sayHello was error,
这个错是什么意思

**Comment by SmartKarven** [comment]
已发现问题所在，非常感谢。
问题原因：dubbo代理服务中的 服务版本号不写，调用不通。
而api中的注释为可选（java的调用方式不写也是可以调用的）。

**Comment by hufeng** [comment]
@SmartKarven 是的 可以试试dubbo-invoker 我们可以动态的调整这些参数 不需要写配置 😆
