### ISSUE TITLE
如何优雅的处理错误？

### ISSUE THREAD

**Issue by lileilei** [dubbo/dubbo2.js#47]
例：
`
router.get('/user', async ctx => {
  const {res, err} = await dubbo.service.demoProvider.getUserInfo();
  ctx.body = res || err.message;
});
`
node端调用rpc服务，service端抛出异常err信息带打印信息不是标准的json对象，不知道问题出在哪里？求指教！！

**Comment by hufeng** [comment]
@lileilei hi阿磊， 不是标准的json对象是什么意思？给我一个小栗子看看，err现在是标准的err对象。

**Comment by lileilei** [comment]
java：
![f0a85f11-3280-2178-5288-43496aa96d7a](https://user-images.githubusercontent.com/7247859/44128971-7a4d4d24-a078-11e8-802d-f64f34d5a562.jpg)

bff端：
![c899d2b6-c1bf-e263-f376-aaf7eab4e64f](https://user-images.githubusercontent.com/7247859/44128954-63a86edc-a078-11e8-9997-f15cc6aabe58.jpg)

err 带打印信息，不是标准json对象

**Comment by hufeng** [comment]
这不是dubbo2.js的处理，而是https://github.com/node-modules/hessian.js/blob/master/lib/object.js#L77 在hessian反序列化的时候序列化成一个err对象。
