### ISSUE TITLE
dubbo2.js通过注册中心调用报错，java dubbo 客户端 调用正常。dubbo2.js直连也正常，为什么呢？

### ISSUE THREAD

**Issue by 15168326318** [dubbo/dubbo2.js#52]
![qq 20180905173319](https://user-images.githubusercontent.com/38483933/45084860-db909680-b131-11e8-9554-994b07274353.png)
报红色这里错。agentList为空，但java dubbo客户端调用是正常的。

**Comment by 15168326318** [comment]
![qq 20180906100617](https://user-images.githubusercontent.com/38483933/45130798-ba28bc80-b1bc-11e8-831d-76c021f206b8.png)
其中undefined是什么意思？一定要版本号？而且我加上了版本号也是这样的问题。

**Comment by hufeng** [comment]
@15168326318 可以开启DEBUG特性，就可以感知到更多的细节

DEBUG=dubbo* 然后启动node进程 

我判断是可能在dubbo初始化的时候，没有service属性，没有告诉dubbo对象 我们要去订阅那些服务。

**Comment by lileilei** [comment]
@hufeng   最终结论是  dubbo.js调用时的声明的版本号一定要与java注册服务时候的版本号一致
