### ISSUE TITLE
支持opentracing+jeager分布式跟踪

### ISSUE THREAD

**Issue by rocky-zh** [dubbo/dubbo2.js#53]
能否支持jeager分布式跟踪（koa-await-breakpoint-jaege）

[https://www.bookstack.cn/read/node-in-debugging/6.4OpenTracingJaeger.md](url)

**Comment by hufeng** [comment]
@rocky-zh 可以的，给我一些时间来实现下，之前在调研忙不过来 耽误了些

**Comment by hufeng** [comment]
@rocky-zh 包括我们packages/zone-context就是为了去解决调用上下文的问题设计的

**Comment by rocky-zh** [comment]
@hufeng 请问目前进展如何？

**Comment by hufeng** [comment]
@rocky-zh 我们内部opentracing已经用起来了 还挺好

**Comment by rocky-zh** [comment]
期待分享

**Comment by lileilei** [comment]
@hufeng  请问支持async_hooks特性的 zone-context  库可以用于生产环境否?  这个库用着挺方便的就是有点小担忧

**Comment by hufeng** [comment]
zone-context一直在我们的生产环境 @lileilei 😆

**Comment by hufeng** [comment]
目前packages下面的模块都在线上得到了检验
经过实战的检验才敢放出来 不能坑小伙伴
不是为了开源而开源 😆

**Comment by lileilei** [comment]
@hufeng  欧克！！

**Comment by hufeng** [comment]
@creasy2010 期待晓得同学能把zipkin方案 open出来
