### ISSUE TITLE
Error: uuid:  invoke com.greenline.sns.share.service.user.SnsUserInfoService#findUserInfoById was error, requestId#1:Could not find any agent worker with com.greenline.sns.share.service.user.SnsUserInfoService#undefined# agentList

### ISSUE THREAD

**Issue by yaphetszmn** [dubbo/dubbo2.js#54]
如图，egg配合dubbo2.js通过zk调用dubbo的时候一直报这个错
![image](https://user-images.githubusercontent.com/37991688/45361051-d46efa00-b603-11e8-988d-c9985bcd1f35.png)

有没有大佬知道的帮忙解决下，开启了 DEBUG=dubbo* 也没有找出问题所在
@hufeng

**Comment by shige8023** [comment]
同样的问题 你怎么解决的

**Comment by cnlinge** [comment]
同问，我也报这个错。

**Comment by JianpanBucuo** [comment]
请问解决了吗。。遇到了这个问题
