### ISSUE TITLE
dubbo直连也没有大神知道怎么弄

### ISSUE THREAD

**Issue by yaphetszmn** [dubbo/dubbo2.js#55]
![333](https://user-images.githubusercontent.com/37991688/45399404-76312e00-b67a-11e8-8a48-f3b5b5089148.png)

如图，我这里直连的时候不知道具体咋弄，官方例子写的不全  求助

**Comment by hufeng** [comment]
@yaphetszmn 文档还需要改进 ^_^ 

dubbo直连的场景是用于快速测试dubbo接口，一般不建议用在生产环境
生产环境还是希望通过注册中心来订阅服务。


```typescript
import {DirectlyDubbo, java} from 'dubbo2.js';

//初始化直连dubbo对象
const directlyDubbo = DirectlyDubbo.from({
 //暴露dubbo服务的地址
  dubboAddress: 'localhost:20880',
//dubbo的版本
  dubboVersion: '2.0.0',
//调用超时时间
  dubboInvokeTimeout: 10,
});

//代理服务
const demoService = dubbo.proxyService<IDemoProvider>({
  dubboInterface: 'com.alibaba.dubbo.demo.DemoProvider',
  methods: {
    findUserByIds(...ids) {
     //可以用js-to-java模块保证符合hessian化参数格式
     return ids;
    }
  },
  version: '1.0.0',
});

//调用服务
(async function main() {
  const {res, err} = await demoService.findUserByIds(1);
 //TODO
})();
```

**Comment by yaphetszmn** [comment]
@hufeng   感谢回答，生产环境是肯定用zk的，只是我们公司内网的zk上根据不同业务线需求，可能会在多台机器部署不同的分支，才想着把直连集成和封装，好让测试方便

现有的这个模式有办法把直连方式做到egg的app对象上吗？ 

这个快速测试的场景在开发侧是方便的，但是测试同学更希望上述我描述的形式~

作者大大有没有什么好的办法或者是否考虑以后支持我的这类需求呢？

**Comment by hufeng** [comment]
@yaphetszmn 
可以直连到egg的app对象上的，我来把example中的egg的demo好好的整理下，稍等 😆

**Comment by yaphetszmn** [comment]
期待~  thank you
