### ISSUE TITLE
失败重试，容错机制

### ISSUE THREAD

**Issue by SmartKarven** [dubbo/dubbo2.js#59]
您好！
    我研究了一下源码，没有发现有失败重试的功能，是不没有实现或者我没有找到对应的代码，是否可以扩展容错的一些机制

**Comment by hufeng** [comment]
hello @SmartKarven 是的目前没有调用失败重试机制，最早的实现是有的，而是也不难实现就是在最大超时时间内，发现调用失败再重新调用下，和公司后端同学沟通 他们觉得重试可能会导致一些问题 因为接口可能不是幂等的 然后就拿掉了这个功能， 如果要做就做成可配置要精确到方法级，接口级，全局级别。

**Comment by hufeng** [comment]
目前在我们内部跑的比较稳定，这段时间有点忙，稍后就会好点，
@SmartKarven 我们可以一起把这些缺失的部分功能给更好的完善起来
包括我提的issue很想能够实时获取线上的dubbo2.js内部的状态，可以很好的trace监控起来
目前我们也有trace的能力，直接subscribe就可以拿到 目前测试下来就是有时候信息很膨胀不够友好
这块还需要完善，做到类似java的jmx 😆体验 就会好好很多。
