### ISSUE TITLE
能否自动从jar包内生成provider

### ISSUE THREAD

**Issue by rickyzenggan** [dubbo/dubbo2.js#62]
类似最下面的代码，如果人工去编写，成本较高，最好能通过JAR包直接生成，这个功能点有没有规划去落地？
/Create the service to be injected
import {Dubbo} from 'dubbo2.js';
const demoProvider = dubbo =>
  dubbo.proxyService({
dubboInterface: 'com.alibaba.dubbo.demo.DemoProvider',
version: '1.0.0',
methods: {
  sayHello(name) {
return [java.String(name)];
  },

  echo() {},

  test() {},

  getUserInfo() {
return [
  java.combine('com.alibaba.dubbo.demo.UserRequest', {
id: 1,
name: 'nodejs',
email: 'node@qianmi.com',
  }),
];
  },
},
  });

**Comment by rickyzenggan** [comment]
localhost:dubbo2.js-master rickyzeng$ interpret -c dubbo.json
read jar ast file /var/folders/kc/6f3gxk8n6tlc_6yys5pnw8_r0000gn/T/jexpose14339011821655624206/output/deflated.json
Translation completed

但是文件未生成，辛苦帮忙看下，如何定位，我是直接拿你库里的JAVA文件编译为JAR包后，再去转换的

**Comment by creasy2010** [comment]
翻译师, 主要职责就是把java代码自动生成 Typescript
根据你的描述 , 我怀疑是配置文件 的entry配置的有问题.. 你的例子应该配置为entry:com.alibaba

相关的错误提示我添加了下.
