### ISSUE TITLE
文件上传方式选择

### ISSUE THREAD

**Issue by lileilei** [dubbo/dubbo2.js#63]
1.直接由浏览器提交到文件服务器没毛病
2.通过dubbo.js 提交只能提交byte数组的方式，byte数组不好解析（不知有没有不写入文件能够直接读取到文件buffer数组，头信息的库）
3.java端文件上传改成restful接口，我bff端通过http上传文件，还要解析才好，目前我是上传成功后提交文件成功然后再删除临时文件的方式

**Comment by hufeng** [comment]
这个是不是不要交给dubbo完成
