### ISSUE TITLE
consumer信息获取和创建consumer失败NODE_EXISTS问题

### ISSUE THREAD

**Issue by allanming** [dubbo/dubbo2.js#64]
在调研过程中发现以下问题：
1. dubbo-url.ts中通过dubbo url获取版本和group信息，没有兼容default.xxx，取到的都是默认值，导致consumer无法创建成功。
2. zookeeper.ts中
```javascript
private async _createConsumer(params: {
    host: string;
    port: number;
    name: string;
    dubboInterface: string;
    dubboVersion: string;
    version: string;
  }) {
    let {host, port, name, dubboInterface, dubboVersion, version} = params;
    const queryParams = {
      host,
      port,
      interface: dubboInterface,
      application: name,
      category: 'consumers',
      dubbo: dubboVersion,
      method: '',
      revision: '',
      version: version,
      side: 'consumer',
      check: 'false',
    };
```

queryParams中的side属性，必须加个随机数或时间戳，否则会报：

`
失败或者consumer已经存在，{ NODE_EXISTS: Exception: NODE_EXISTS[-110] at ConnectionManager.onSocketData (/home/xxx/work/node/dubbo-koa/node_modules/node-zookeeper-client/lib/ConnectionManager.js:570:35) at ConnectionManager.onSocketData (/home/xxx/work/node/dubbo-koa/node_modules/node-zookeeper-client/lib/ConnectionManager.js:580:14) at emitOne (events.js:116:13) at Socket.emit (events.js:211:7) at addChunk (_stream_readable.js:263:12) at readableAddChunk (_stream_readable.js:250:11) at Socket.Readable.push (_stream_readable.js:208:10) at TCP.onread (net.js:607:20) code: -110, name: 'NODE_EXISTS', path: undefined, message: 'Exception: NODE_EXISTS[-110]' }\
`

该方法拼接后的url为：

`
check consumer url: /dubbo/com.ztjy.article.facade.ArticleFacade/consumers/consumer://172.16.202.62/com.ztjy.article.facade.ArticleFacade?host=172.16.200.17&port=50001&interface=com.ztjy.article.facade.ArticleFacade&application=dubbo-node-consumeraa&category=consumers&dubbo=2.6.0&method=&revision=&version=4.0.0&side=consumer&check=false
`

从Dubbo Admin中看Java服务的consumer信息为：

`
consumer://xx.xx.xx.xx/test/com.xxx.article.facade.ArticleFacade?application=xx-server&category=consumers&check=false&default.group=test&dubbo=2.6.0&interface=com.xxx.article.facade.ArticleFacade&methods=getArticleByAuthorId,updateArticle,addArticle,getArticleWithStatus,batchArticleForList,getArticle,getArticleCountByAuthorId,batchArticleWithStatus,batchArticle,deleteArticle&pid=1873&revision=1.0.3-SNAPSHOT&side=consumer×tamp=1539606199032
`

side加了时间戳，通过给zookeeper.ts中的side加时间戳，最后成功创建consumer并正常返回了数据。

以上两点，辛苦作者尽快修复，感谢！

**Comment by allanming** [comment]
```
private constructor(providerUrl: string) {
    log('DubboUrl from -> %s', providerUrl);
    this._url = url.parse(providerUrl);
    this._query = qs.parse(providerUrl) as any;

    this.host = this._url.hostname;
    this.port = Number(this._url.port);
    this.path = this._url.pathname.substring(1);
    this.dubboVersion = this._query.dubbo || '';
    this.version = this._query.version || '0.0.0';
    this.group = this._query.group || '';
  }
```
version的默认值最好为空，0.0.0我这会报错，使用者的配置都不同。

**Comment by hufeng** [comment]
hello @allanming group version我会进一步改进，目前我想到了一些不错的办法，非常有意思，我们可以和dubbo-invoker去结合起来，这样一次配置到处生效。

最早consumer的版本是有随机数的，导致了我们线上的一个bug，比如dubbo的服务提供方在频繁升级中，导致我们的zk不断的收到监听 然后不断地写入consumer，导致zookeeper中被写入大量的数据，导致zk僵死，😭所以我们干掉了随机数。干掉随机数就会出现node节点再去创建会有这个报错，其实没有关系，后面代码可以先做一次判断，然后才去写入。

**Comment by allanming** [comment]
> hello @allanming group version我会进一步改进，目前我想到了一些不错的办法，非常有意思，我们可以和dubbo-invoker去结合起来，这样一次配置到处生效。
> 
> 最早consumer的版本是有随机数的，导致了我们线上的一个bug，比如dubbo的服务提供方在频繁升级中，导致我们的zk不断的收到监听 然后不断地写入consumer，导致zookeeper中被写入大量的数据，导致zk僵死，😭所以我们干掉了随机数。干掉随机数就会出现node节点再去创建会有这个报错，其实没有关系，后面代码可以先做一次判断，然后才去写入。

我现在改了下源码先用着哈，期待优化后的版本！基于TypeScirpt和egg开发的小项目，本来想用dubbo-invoker，统一将dubbo接口的配置放到config中，结果没成功(主要是没完全按你的demo来)，后来一着急，通过传参的方式(传app)获取config实现的，后面我再抽时间研究下dubbo-invoker。感谢！

**Comment by hufeng** [comment]
其实你的方式也非常好，dubbo-invoker主要可以提供一些灵活性，比如全接口名匹配，正则匹配，代码特殊匹配，另外可以做一层薄薄的缓存，这样就不要每次去匹配了 😆

**Comment by ztjy-fe** [comment]
> @hufeng 现在最新版本应该是使用 dubboSetting 替代 dubbo-invoker 的吧？还是有这个问题啊。。。
> 
> ```
> create successfully consumer url: /dubbo/cc.ewell.dict.api.service.IxDictService/consumers/consumer:
> //xxx.xx.xx.xx/cc.ewell.dict.api.service.IxDictService?host=xxx.xx.xx.xx&port=20881&interface=cc.ewell.dict.api.ser
> vice.IxDictService&application=ewell-medrec-web&category=consumers&dubbo=2.0.2&method=&revision=&version=1.0.0&group=&
> side=consumer&check=false +30ms
>   dubbo:zookeeper check consumer url: /dubbo/cc.ewell.dict.api.service.IxDictService/consumers/consumer://xxx.xx.x.xx/cc.ewell.dict.api.service.IxDictService?host=xxx.xx.xx.x&port=20881&interface=cc.ewell.dict.api.service.IxDictSer
> vice&application=ewell-medrec-web&category=consumers&dubbo=2.0.2&method=&revision=&version=1.0.0&group=&side=consumer&
> check=false创建consumer失败 { Exception: NODE_EXISTS[-110] at ConnectionManager.onSocketData (D:\2018\medrec-web\node_
> modules\node-zookeeper-client\lib\ConnectionManager.js:570:35) at ConnectionManager.onSocketData (D:\2018\medrec-web\n
> ode_modules\node-zookeeper-client\lib\ConnectionManager.js:580:14) at emitOne (events.js:116:13) at Socket.emit (event
> s.js:211:7) at addChunk (_stream_readable.js:263:12) at readableAddChunk (_stream_readable.js:250:11) at Socket.Readab
> le.push (_stream_readable.js:208:10) at TCP.onread (net.js:597:20) code: -110, name: 'NODE_EXISTS', path: undefined, m
> essage: 'Exception: NODE_EXISTS[-110]' } +19ms
>   dubbo:zookeeper getChildren /dubbo/cc.ewell.nurse.api.service.IOrderExeRecService/providers error Exception: NO_NODE
> [-101] +8ms
> ```
> 调用服务方法后返回的err错误是
> 
> Error: Unknown result flag, expect '0' '1' '2', get 4)

你的consumerurl中的side参数后面加个随机数试试，`side=consumer1241351531351`

**Comment by allanming** [comment]
> @hufeng 现在最新版本应该是使用 dubboSetting 替代 dubbo-invoker 的吧？还是有这个问题啊。。。
> 
> ```
> create successfully consumer url: /dubbo/cc.ewell.dict.api.service.IxDictService/consumers/consumer:
> //xxx.xx.xx.xx/cc.ewell.dict.api.service.IxDictService?host=xxx.xx.xx.xx&port=20881&interface=cc.ewell.dict.api.ser
> vice.IxDictService&application=ewell-medrec-web&category=consumers&dubbo=2.0.2&method=&revision=&version=1.0.0&group=&
> side=consumer&check=false +30ms
>   dubbo:zookeeper check consumer url: /dubbo/cc.ewell.dict.api.service.IxDictService/consumers/consumer://xxx.xx.x.xx/cc.ewell.dict.api.service.IxDictService?host=xxx.xx.xx.x&port=20881&interface=cc.ewell.dict.api.service.IxDictSer
> vice&application=ewell-medrec-web&category=consumers&dubbo=2.0.2&method=&revision=&version=1.0.0&group=&side=consumer&
> check=false创建consumer失败 { Exception: NODE_EXISTS[-110] at ConnectionManager.onSocketData (D:\2018\medrec-web\node_
> modules\node-zookeeper-client\lib\ConnectionManager.js:570:35) at ConnectionManager.onSocketData (D:\2018\medrec-web\n
> ode_modules\node-zookeeper-client\lib\ConnectionManager.js:580:14) at emitOne (events.js:116:13) at Socket.emit (event
> s.js:211:7) at addChunk (_stream_readable.js:263:12) at readableAddChunk (_stream_readable.js:250:11) at Socket.Readab
> le.push (_stream_readable.js:208:10) at TCP.onread (net.js:597:20) code: -110, name: 'NODE_EXISTS', path: undefined, m
> essage: 'Exception: NODE_EXISTS[-110]' } +19ms
>   dubbo:zookeeper getChildren /dubbo/cc.ewell.nurse.api.service.IOrderExeRecService/providers error Exception: NO_NODE
> [-101] +8ms
> ```
> 调用服务方法后返回的err错误是
> 
> Error: Unknown result flag, expect '0' '1' '2', get 4)

你在 `consumer url: /dubbo/cc.ewell.dict.api.service.IxDictService/consumers/consumer:
//xxx.xx.xx.xx/cc.ewell.dict.api.service.IxDictService?host=xxx.xx.xx.xx&port=20881&interface=cc.ewell.dict.api.ser
vice.IxDictService&application=ewell-medrec-web&category=consumers&dubbo=2.0.2&method=&revision=&version=1.0.0&group=&
side=consumer&check=false`url中的side参数的值加上随机数试试 `side=consumer23147135135`

**Comment by hufeng** [comment]
@allanming 升级到dubbo2.js@2.3.7就可以了。
https://github.com/dubbo/dubbo2.js/releases/tag/dubbo2.js%402.3.7

**Comment by allanming** [comment]
> @allanming 升级到dubbo2.js@2.3.7就可以了。
> https://github.com/dubbo/dubbo2.js/releases/tag/dubbo2.js%402.3.7

收到，感谢！

**Comment by lileilei** [comment]
支持flag345了？？完美！！感谢@hufeng 
@allanming

**Comment by lileilei** [comment]
@hufeng 
![us83qzk okqbsqiausajvxu](https://user-images.githubusercontent.com/7247859/50220968-b6692080-03ce-11e9-8e5f-b41b691ffd68.png)
这个不加 不支持全局版本号问题啊。。

**Comment by hufeng** [comment]
囧，这个漏掉了 我明天就合入进来，再发布一个版本

阿磊 <notifications@github.com> 于2018年12月19日周三 下午8:44写道：

**Comment by hufeng** [comment]
@lileilei dubbo2.js@2.3.8合入了default.version
https://github.com/dubbo/dubbo2.js/releases/tag/dubbo2.js%402.3.8
