### ISSUE TITLE
使用interceptor时报错

### ISSUE THREAD

**Issue by AtrisMio** [dubbo/dubbo2.js#65]
Failed to extract ast from java class
Error: exitCode:1  errorInfo:Exception in thread "main" java.lang.IllegalArgumentException: malformed path of entry jar
	at com.hsiaosiyuan.jexpose.ProvidersDeflator.<init>(ProvidersDeflator.java:40)
	at com.hsiaosiyuan.jexpose.App.main(App.java:18)

会抛出异常   malformed path of entry jar，电脑是macOS 10.14 mojave

**Comment by hufeng** [comment]
@creasy2010 晓东同学抽空帮助看下。

**Comment by creasy2010** [comment]
@AtrisMio 能不能提供更多信息.

**Comment by AtrisMio** [comment]
@creasy2010 额，，，主要没法给出最小demo，不带业务代码的不出问题。。。

**Comment by creasy2010** [comment]
我看看是从jar中抽取信息出错了. 
你可以到.https://github.com/hsiaosiyuan0/jexpose 这个项目把源代码拿下来在本地跑,

**Comment by hsiaosiyuan0** [comment]
看报错信息应该是 `-entry-jar` 指定的路径定位不到 jar 文件

**Comment by billowqiu** [comment]
http://dubbo.io/dubbo2.js/docs/interpret.html
按照这个页面来的，同样报错，请问interpret是不是没法单独使用？

文件路径配置不正确:
exitCode:1  errorInfo:Exception in thread "main" java.lang.IllegalArgumentException: malformed path of lib directory
	at com.hsiaosiyuan.jexpose.ProvidersDeflator.<init>(ProvidersDeflator.java:44)
	at com.hsiaosiyuan.jexpose.App.main(App.java:18)

“你可以到.https://github.com/hsiaosiyuan0/jexpose 这个项目把源代码拿下来在本地跑,”
必须使用jexpose本地跑么？

**Comment by creasy2010** [comment]
@billowqiu 查看下lib目录 地址对吗 ?

**Comment by billowqiu** [comment]
cat dubbo.json 
{
    "output": "./src",
    "entry": "",
    "entryJarPath": "sample.jar",
    "libDirPath": ""
}

**Comment by creasy2010** [comment]
libDirPath路径 没有配置导致的.. 

内部有个服务 准备开源出来,目前还在修代码. . 有兴趣一起搞呀.  
![image](https://user-images.githubusercontent.com/1592277/51900101-63cc4c80-23ef-11e9-8540-7ed883d05cee.png)

**Comment by creasy2010** [comment]
@billowqiu 一键启动的例子出炉了, https://github.com/creasy2010/interpret-example/

另附上视频一个  
https://github.com/creasy2010/interpret-example/blob/master/doc/%E8%A7%86%E9%A2%91%E6%95%99%E7%A8%8B.mp4

**Comment by billowqiu** [comment]
高效啊
