### ISSUE TITLE
翻译师版本号配置

### ISSUE THREAD

**Issue by lileilei** [dubbo/dubbo2.js#66]
**Is your feature request related to a problem? Please describe.**
注册中心代理方法的地方需要设置版本号，翻译师默认没有生成

**Describe the solution you'd like**
变量需要一个方便的统一配置地方

**Describe alternatives you've considered**
配置到dubbo.json？ 

**Additional context**
文件：dubbo2.js\packages\interpret-cli\src\transfer\provider\to-proxy-function.ts
![w3v t4w43o0c t1 k ykgjb](https://user-images.githubusercontent.com/7247859/47891567-b351b980-de8e-11e8-8f2d-2561b8aa7755.png)

**Comment by creasy2010** [comment]
hi  ,dubbo-invoker 可以实现这块的配置.. 

https://github.com/dubbo/dubbo2.js/#dubbo-invoker

**Comment by hufeng** [comment]
@lileilei 早期我们也是这样想的，想了很多的办法，实际上这不符合dubbo的调用的，dubbo支持group,version等参数对调用链路做区分，这些参数应该是动态的指定，在dubbo中通常会提供dubbo-provider.xml,dubbo-consumer.xml的配置文件，类似项目中的java/example

但是我们又不想想xml配置那么重，所以我们借助js的动态能力设计了dubbo-invoker, 支持全接口名匹配，和正则，thunk function匹配。
