### ISSUE TITLE
关于请求超时机制 + socketPool的讨论

### ISSUE THREAD

**Issue by mejustme** [dubbo/dubbo2.js#68]
现在请求被放入queue, 此时就会进入超时计时。
- 现象
  队列前面第一个请求到dubbo超时获取时间太长，会导致队列后面所有接口超时
- 思考 
  然后我看了源码，现在对zk返回的多个服务地址有agent负载均衡，但是每个agent里socket 是1，而且现在还不支持 socketPool 的数量的配置，这样超时风险有点大，性能也会有很大限制
- 讨论
  不知道我理解的是否正确，是否有后续的打算，或者什么原因是目前这种方式，谢谢~

**Comment by hufeng** [comment]
hi @mejustme 

有没有测试代码，以及使用的版本

按照道理不该是这样的现象，超时时间和调用的上下文绑定的，也就是超时时间是设置在每个放入队列的上下文，
```typescript
add = (ctx: Context) => {
    return new Promise((resolve, reject) => {
      ctx.resolve = resolve;
      ctx.reject = reject;

      //hessian参数检测
      if (!Queue._checkMethodArgsHessianType(ctx)) {
        return;
      }
      //timeout超时检测
      this._checkTimeout(ctx);
      //add queue
      const {requestId, dubboInterface} = ctx.request;
      log(`add queue,requestId#${requestId}, interface: ${dubboInterface}`);
      //设置调用队列
      this._requestQueue.set(requestId, ctx);
      if (isDevEnv) {
        log(`current schedule queue =>`, this.scheduleQueue);
      }
      //通知scheduler
      this._subscriber(requestId, ctx);
    });
  };

 /**
   * 超时检测
   * @param ctx
   */
  private _checkTimeout(ctx: Context) {
    //先获取上下文设置的超时时间，如果没有设置就获取最大超时时间
    const timeout = (ctx.timeout || config.dubboInvokeTimeout) * 1000;
    log('check timeout: ctx.timeout-> %d @timeout: %d', ctx.timeout, timeout);

    ctx.timeoutId = setTimeout(() => {
      statistics.timeoutErrCount++;
      const {requestId, dubboInterface, methodName} = ctx.request;

      log(`err: ${dubboInterface}#${methodName} remote invoke timeout`);

      this.failed(
        requestId,
        new DubboTimeoutError(
          `err:${dubboInterface}#${methodName} remote invoke timeout`,
        ),
      );
    }, timeout);
  }
```

如果失败，也是根据当前context中的requestId去进行失败处理，删除队列。

SocketPool之前是有的(默认分配4个socket)，后来在我们线上实际跑也有些问题，就是会创建大量的Socket连接。
Why?

比如我们调用了100个服务，分布在10台机器上，那就会10 * 4 * (node进程数)，实际上服务或者机器的数量会常常大于这个。


所以考虑到现在dubbo服务都是多负载，那就创建一个socket与其对应，我们的node也是多进程，另外我们把socket-worker的retry做的健壮，也是可以解决这个问题。
socket只是一个通道，node本身是no-block io 性能不会有太多的损失在这个上面,更多是dubbo服务返回的速度，我测试过，单node进程，一个socket， dubbo服务一个hello world.
node10 可以上9k的qps。

目前我们线上这样看，内存降了不少，cpu也是，稳定性也很好。

**Comment by mejustme** [comment]
> hi @mejustme
> 
> 有没有测试代码，以及使用的版本
> 
> 按照道理不该是这样的现象，超时时间和调用的上下文绑定的，也就是超时时间是设置在每个放入队列的上下文，
> 
> ```ts
> add = (ctx: Context) => {
>     return new Promise((resolve, reject) => {
>       ctx.resolve = resolve;
>       ctx.reject = reject;
> 
>       //hessian参数检测
>       if (!Queue._checkMethodArgsHessianType(ctx)) {
>         return;
>       }
>       //timeout超时检测
>       this._checkTimeout(ctx);
>       //add queue
>       const {requestId, dubboInterface} = ctx.request;
>       log(`add queue,requestId#${requestId}, interface: ${dubboInterface}`);
>       //设置调用队列
>       this._requestQueue.set(requestId, ctx);
>       if (isDevEnv) {
>         log(`current schedule queue =>`, this.scheduleQueue);
>       }
>       //通知scheduler
>       this._subscriber(requestId, ctx);
>     });
>   };
> 
>  /**
>    * 超时检测
>    * @param ctx
>    */
>   private _checkTimeout(ctx: Context) {
>     //先获取上下文设置的超时时间，如果没有设置就获取最大超时时间
>     const timeout = (ctx.timeout || config.dubboInvokeTimeout) * 1000;
>     log('check timeout: ctx.timeout-> %d @timeout: %d', ctx.timeout, timeout);
> 
>     ctx.timeoutId = setTimeout(() => {
>       statistics.timeoutErrCount++;
>       const {requestId, dubboInterface, methodName} = ctx.request;
> 
>       log(`err: ${dubboInterface}#${methodName} remote invoke timeout`);
> 
>       this.failed(
>         requestId,
>         new DubboTimeoutError(
>           `err:${dubboInterface}#${methodName} remote invoke timeout`,
>         ),
>       );
>     }, timeout);
>   }
> ```
> 
> 如果失败，也是根据当前context中的requestId去进行失败处理，删除队列。
> 
> SocketPool之前是有的(默认分配4个socket)，后来在我们线上实际跑也有些问题，就是会创建大量的Socket连接。
> Why?
> 
> 比如我们调用了100个服务，分布在10台机器上，那就会10 * 4 * (node进程数)，实际上服务或者机器的数量会常常大于这个。
> 
> 所以考虑到现在dubbo服务都是多负载，那就创建一个socket与其对应，我们的node也是多进程，另外我们把socket-worker的retry做的健壮，也是可以解决这个问题。
> socket只是一个通道，node本身是no-block io 性能不会有太多的损失在这个上面,更多是dubbo服务返回的速度，我测试过，单node进程，一个socket， dubbo服务一个hello world.
> node10 可以上9k的qps。
> 
> 目前我们线上这样看，内存降了不少，cpu也是，稳定性也很好。

首先感谢细心的回复
1. 关于超时的问题，每个请求进来调用add() 函数，
```
add = (ctx: Context) => {
    //timeout超时检测
      this._checkTimeout(ctx); 
}

  private _checkTimeout(ctx: Context) {
    // ...... 
    // 此时setTimeout 超时倒计时已经开始, 即，放入待消费队列里就进行了倒计时，
    // 意味着队列中每个请求的时间和队列长度，直接影响到队列中后面请求是否成功
    // 再加之只有一个tcp socket，面对dubbo请求返回时间长，请求数量大，会出现大量请求失败的场景。
    ctx.timeoutId = setTimeout(() => {
      this.failed(
        requestId,
        new DubboTimeoutError(
          `err:${dubboInterface}#${methodName} remote invoke timeout`,
        ),
      );
    }, timeout);
  }
```
如上注释，对问题的描述

2. 关于sock 缓存池问题，感谢描述了服务数*node多进程数会产生的太多socket问题，以及对该一个socket重试机制来保证稳定性。
   - socket pool 可以提高并发处理请求问题，性能很大提高，希望能支持配置，让使用者根据场景配置

**Comment by hufeng** [comment]
hello @mejustme 
其实不是一个tcp socket，如果dubbo的服务提供方有几个负载就会有几个socket与其对应，
然后我们随机选择一个进行发送接收。

我补一个测试场景，来验证下这个超时的问题。

**Comment by mejustme** [comment]
> hello @mejustme
> 其实不是一个tcp socket，如果dubbo的服务提供方有几个负载就会有几个socket与其对应，
> 然后我们随机选择一个进行发送接收。
> 
> 我补一个测试场景，来验证下这个超时的问题。

恩好的，你可以补充个测试用例。我最上头提问的思考里描述了，“现在对zk返回的多个服务地址有agent负载均衡，但是每个agent里socket 是1”

**Comment by hufeng** [comment]
@mejustme 确实可配置更好一点 根据不同的场景有调整的能力

**Comment by lianxuify** [comment]
@hufeng  cnode 提问 https://cnodejs.org/topic/5bf3ae57e6481c5709f5d76c

**Comment by hufeng** [comment]
@mejustme TCP长连接，node的socket是非阻塞的io，java后端对应了一个线程池，返回不是按照请求1，2，3的顺序返回，而是谁先处理完谁返回，比如返回响应1会保证响应1的包体顺序.

![image](https://user-images.githubusercontent.com/533008/49682635-7e223200-faf2-11e8-9d46-db87188dd05a.png)

**Comment by hufeng** [comment]
@mejustme tcp会保证传输的顺序，已经在传输request=2了，就不会夹杂其他的了 不然就没有办法解析了
