### ISSUE TITLE
拉取hello-egg，运行报错

### ISSUE THREAD

**Issue by dsky1990** [dubbo/dubbo2.js#69]
![image](https://user-images.githubusercontent.com/1579516/48418469-54dee200-e790-11e8-9e0d-1401d91b4192.png)

**Comment by dsky1990** [comment]
@hufeng 求助

**Comment by hufeng** [comment]
@dsky1990 拉去下最新代码可以了 尴尬 每个版本的typescript也会有些细微的差别

如果是mac
```
brew install zookeeper
brew services start zookeeper
#启动java provider
java/dubbo-demo/dubbo-demo-provider/src/main/java/com/alibaba/dubbo/demo/provider/Provider.java
```

![image](https://user-images.githubusercontent.com/533008/48422929-96748a80-e79a-11e8-81a8-89b0d5694b46.png)

![image](https://user-images.githubusercontent.com/533008/48422950-9f655c00-e79a-11e8-9404-56ac85469c93.png)

**Comment by dsky1990** [comment]
好滴，我试试，感谢🙏

**Comment by dsky1990** [comment]
![image](https://user-images.githubusercontent.com/1579516/48424357-709cb500-e79d-11e8-8a22-af6384dfb5e4.png)
`interpret-util`这个package缺失，add一下就好了

**Comment by hufeng** [comment]
@dsky1990 😆给个pr给我

**Comment by dsky1990** [comment]
@hufeng 已提交
