### ISSUE TITLE
DUBBO_RESPONSE_BODY_FLAG只支持0，1，2？

### ISSUE THREAD

**Issue by rocky-zh** [dubbo/dubbo2.js#74]
decode.ts中只支持

```javascript
RESPONSE_WITH_EXCEPTION = 0,
RESPONSE_VALUE = 1,
RESPONSE_NULL_VALUE = 2,
```

RESPONSE_NULL_VALUE_WITH_ATTACHMENTS
RESPONSE_VALUE_WITH_ATTACHMENTS
RESPONSE_WITH_EXCEPTION_WITH_ATTACHMENTS

后三种的支持不知道有无计划？

**Comment by rocky-zh** [comment]
建议开几次视频代码讲座，也促进一下生态。刚开始看dubbo2.js，有点晕

**Comment by hufeng** [comment]
@lileilei 同学已经给出了pr 我尽快review下 然后merge

**Comment by hufeng** [comment]
@rocky-zh 文档还需要持续优化，写文档真是体力活 https://github.com/hufeng/iThink/tree/master/talk 这个之前在内部做的分享 可以看到很多背后的故事

**Comment by rocky-zh** [comment]
@hufeng 

 看过 @lileilei 提交的pr，封装的

```javascript
  if (err) {
      queue.failed(requestId, err);
    } else {
      queue.resolve(requestId, res);
    }
```

以及queue里边都需要改参数，将resProp隐参送进去，这个太核心了，建议你亲自动个手

**Comment by hufeng** [comment]
@rocky-zh 我会review下代码保证最大的api的舒适性

**Comment by hufeng** [comment]
@rocky-zh @lileilei 看了最新的dubbo的java代码 对于使用场景有些认知 感觉不需要把attachment这个值合入到返回值中，我们有很好的middleware的机制可以很好的扩展，直接把这个值挂在在context就可以了。这样对我们现在的架构改动最小。

设想：
```javascript
dubbo.use(async (ctx, next) => {
   //before
   await next();
  //after
  console.log(ctx.dubboResponseAttachments);
})
```

**Comment by hufeng** [comment]
dubbo2.js@2.6.7
https://github.com/dubbo/dubbo2.js/releases/tag/dubbo2.js%402.3.7
