### ISSUE TITLE
dubbo2.js能支持泛化调用么？

### ISSUE THREAD

**Issue by kujinyun** [dubbo/dubbo2.js#78]
和Java里的GenericService类似的功能，否则要生成一堆interface对于一个API网关来说就很不方便了。谢谢

**Comment by hufeng** [comment]
@kujinyun 能详细描述下吗？

**Comment by kujinyun** [comment]
类似于:
const interface = "com.xxx.echoservice";
const method = "sayhello";
const proxyService = new ProxyService(interface);
proxyService.invoke(method, args)

**Comment by hufeng** [comment]
等我来了解下 dubbo的泛化调用 先close

**Comment by sunchuanleihit** [comment]
可以在调用前再封装个泛化调用的模块，生成的方法里都有参数类型，在泛化调用的时候可以再做转换

**Comment by hanlukk** [comment]
现在支持了吗??
