### ISSUE TITLE
Can I get egg's request instance in dubbo's middleware?

### ISSUE THREAD

**Issue by lavyun** [dubbo/dubbo2.js#81]
**Describe the solution you'd like**
I have a full link requirement,  I want to use egg's request in dubbo's middleware. Whether to consider mixing egg's request in dobbo's context?

**Comment by hufeng** [comment]
@lavyun let me think about it.

**Comment by lavyun** [comment]
Now, I cache the egg's request instance into memory to solve this problem, but this is definitely not very good.

**Comment by hufeng** [comment]
@lavyun 

I think the most elegant way is to use zone-context (source code dubbo2.js/packages/zone-context)

You can write a egg middleware
```js
module.exports = (ctx, next) => {
   zoneContext.setRootContext('url', context.xx);
   await next();
}
```

in dubbo2.js middleware
```javascript
dubbo.use((ctx, next) => {
  ctx.attachment = {url: zoneContext.get('url')}
  await next();
});
```

**Comment by hufeng** [comment]
@lavyun enjoy :)
